version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: app-tourism
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - network

    mysql:
        image: mysql
        container_name: db-tourism
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '<root-password>'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./database/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
        networks:
            - network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - network

    redis:
        container_name: redis-tourism
        image: redis:latest
        networks:
            - network

networks:
    network:
        driver: bridge
